name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: jitterbit/get-changed-files@v1
        id: changes
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.changes.outputs.all }}"
          if: startsWith("${{ steps.changes.outputs.all }}, 'github1')
            env:
              accessibility_required = true
          echo ${{accessibility_required}}
