name: Test
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fl: ['core-services/','events-api/','http-api/','auth-api/','model/','ui/src']
    steps:
      - name: arr
        run: |
          echo ${{ matrix.fl }}
      
